// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  spec3

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Contact ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Contact ) UnmarshalJSON([]byte) error { return nil }
func ( Contact ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Contact ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Contact *Contact
